### ISSUE TITLE
LoadError: cannot load such file -- tasks/emoji.rake

### ISSUE THREAD

**Issue by jlubeck** [sofetch/standupbot-open-source#83]
Hey, when trying to install this no my local machine, when creating the DB and running:

`rake db:create db:migrate`

I get this error:
```
rake aborted!
LoadError: cannot load such file -- tasks/emoji.rake
/home/ubuntu/standupbot-open-source/Rakefile:4:in `load'
/home/ubuntu/standupbot-open-source/Rakefile:4:in `<top (required)>'
```

Any ideas?
Thanks!

**Comment by jlubeck** [comment]
Ok, if I use the bundled rake (bin/rake) instead of plain rake the command works (you might want to think about updating the docs), but now I'm getting new errors:


```
I, [2016-09-13T15:17:19.812616 #14994]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
FATAL:  role "ubuntu" does not exist
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:87:in `connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/postgresql_database_tasks.rb:8:in `connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/postgresql_database_tasks.rb:17:in `create'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:93:in `create'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:274:in `each'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/standupbot-open-source/bin/rake:8:in `<top (required)>'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/ubuntu/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"fetch_bot_development"}
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "ubuntu" does not exist
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:87:in `connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:913:in `initialize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `new'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `up'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
PG::ConnectionBad: FATAL:  role "ubuntu" does not exist
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_handling.rb:87:in `connection'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:913:in `initialize'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `new'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `up'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/ubuntu/.gem/ruby/2.3.0/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.gem/ruby/2.3.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/command_wrapper.rb:40:in `call'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:183:in `block in serve'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:156:in `fork'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:156:in `serve'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
/home/ubuntu/.gem/ruby/2.3.0/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jlubeck** [comment]
Ok, needed to add the ubuntu role/user:

`sudo -u postgres createuser ubuntu -s`

tables created now. Not closing it yet in case you want to modify the instructions for installing.
